# Generated by Django 2.1 on 2019-05-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='profile',
            new_name='customer',
        ),
    ]
