# Generated by Django 2.1 on 2019-05-07 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0002_auto_20190507_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.Profile')),
                ('stock_item', models.ManyToManyField(blank=True, to='products.Item', verbose_name='purchased items')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
