# Generated by Django 2.1 on 2019-05-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20190507_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stock_item',
            field=models.ManyToManyField(blank=True, to='products.Item', verbose_name='purchase items'),
        ),
    ]
