# Generated by Django 2.1 on 2019-05-19 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190519_1643'),
        ('customers', '0005_auto_20190512_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total')),
                ('completed', models.BooleanField(default=False)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='placed')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customers.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='stock_items',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='order',
            name='stock_items',
            field=models.ManyToManyField(blank=True, through='customers.StockItem', to='products.Item'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.Order'),
            preserve_default=False,
        ),
    ]
