# Generated by Django 2.1 on 2019-05-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20190519_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'purchase'), ('RENTAL', 'rental')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
