# Generated by Django 2.1 on 2019-05-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[(0, 'purchase'), (1, 'rental')], max_length=8),
        ),
    ]
