# Generated by Django 2.1 on 2019-05-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20190519_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'purchase'), ('RENTAL', 'rental')], max_length=8),
        ),
    ]
