# Generated by Django 2.1 on 2019-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_service_component',
            field=models.BooleanField(default=False, verbose_name='service component'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=70, verbose_name='product'),
        ),
    ]
